# $schema: https://raw.githubusercontent.com/z1-0/ah.sh/main/src/assets/config.schema.json

# Provider type: devenv or dev-templates
provider = "dev-templates"

# Leave empty to use the $SHELL environment variable
# shell = "zsh"
